### ISSUE TITLE
用最新源码部署 GAE 服务端报错了

### ISSUE THREAD

**Issue by jzp820927** [yinqiwen/gsnova#36]
10:16 PM Error 422: --- begin server output ---
Compile failed:
2016/09/29 07:16:11 go-app-builder: build timing: 8×compile (1.586s total), 0×link (0 total)
2016/09/29 07:16:11 go-app-builder: failed running compile: exit status 1

web.go:68: undefined: c
--- end server output ---
10:16 PM Rolling back the update.
Error 422: --- begin server output ---

--- end server output ---

**Comment by yinqiwen** [comment]
fixed
