### ISSUE TITLE
vps(arukas) HTTPProxy  ---- No proxy found

### ISSUE THREAD

**Issue by MeABc** [yinqiwen/gsnova#39]
已在 client.json 里把 HTTPProxy 改为 "Proxy":"http://127.0.0.1:8087"

日志
![image](https://cloud.githubusercontent.com/assets/18194126/19425396/74826c66-9464-11e6-8eae-72cd71cd9af8.png)

**Comment by MeABc** [comment]
补充，我用的是自编译。

**Comment by jzp820927** [comment]
检查下两边的 key 是否一致。

**Comment by MeABc** [comment]
不加 HTTPProxy  是可以正常用的

**Comment by jzp820927** [comment]
好吧，那就只有等 Y大来帮你解决了。

**Comment by MeABc** [comment]
再附个正常用的

![image](https://cloud.githubusercontent.com/assets/18194126/19425969/4a910a3c-946b-11e6-8dcb-7c51c5a16467.png)

**Comment by yinqiwen** [comment]
vps模式配置的proxy需要支持HTTP Connect方法，就是所谓的https proxy

**Comment by jzp820927** [comment]
GAE 是不支持的。

**Comment by wz7465** [comment]
@yinqiwen 
//if u are behind a HTTP proxy
 "HTTPProxy":"",
这里的HTTPProxy是指后置代理吗？vps->HTTPProxy
有没有前置代理的设置？
比如我不想sniproxy->gae 而想本地127.0.0.1:1080->gae

**Comment by yinqiwen** [comment]
指的是  local->HTTP Proxy->vps

**Comment by devcodewak** [comment]
@wz7465 这个是前置代理。  local -> Proxy -> vps， 也可 local -> Proxy -> GAE
另 新版本配置中应写 “Proxy”: "xxx.xxx.xx.xxx"，而不是"HttpProxy"， 这个y大还没改过来

另看代码这个Proxy仅 https的，应不支持socks5

**Comment by wz7465** [comment]
@devcodewak 
具体格式怎么写？
我这样写的
                        "Enable":true,
			"Type":"gae",
			"Name":"mygae",
            "ServerList":["gsnovaxx"],
			"SNI":["www.google.com.hk", "www.google.co.jp"],
			"Proxy":"xxx.xxx.xxx.xxx:0000",(也试过"Proxy":"http://xxx.xxx.xxx.xxx:0000"）
ip填过127.0.0.1:1111这种类型的，有socks也有http，不行
找了个squid代理，按说明应该是支持http connect方式的（162.208.8.9:25),也没成功

**Comment by MeABc** [comment]
同楼上。并附上我的日志。8080同时支持 http/https proxy 。

![2016-10-17_203942](https://cloud.githubusercontent.com/assets/18194126/19439848/3c827b3c-94b2-11e6-9a3c-9766edfeafae.png)

![2016-10-17_204352](https://cloud.githubusercontent.com/assets/18194126/19439853/40999f34-94b2-11e6-97d7-aaaa8c6d5d82.png)

**Comment by yinqiwen** [comment]
配置 "Proxy":"http://xxx.xxx.xxx.xxx:8080"  这个是对的，但是这个proxy回了403 forbidon说明被禁掉了，可能需要用户名密码

**Comment by wz7465** [comment]
@yinqiwen 
我测试过了，这类前置代理只支持heroku平台，不支持gae
即便支持heroku平台，路由规则与前面设置起冲突，能访问被屏蔽的网站，国内直连的网站反而不能访问了

**Comment by wz7465** [comment]
@yinqiwen 
说错了，路由规则没有问题，是测试过程中直连被关掉了

**Comment by wz7465** [comment]
软件的穿墙能力还不强，用heroku平台的wss模式，几分钟就会被墙侦测干扰，加前置，用了一段时间，开始还较稳定，但后来log出现会话数到6000多个，有大量的io timeout，基本不能用了，
用gae+sniproxy性能不错，但是sniproxy ip 优选有问题，不能有bad ip，放了两个ip测，其中一个无效，代理就不能工作了

**Comment by MeABc** [comment]
@yinqiwen 8080这个是无须身份认证的。

（先把这个 issue 关了，因可能不能即时回复）
