### ISSUE TITLE
请问 pass 去哪了？

### ISSUE THREAD

**Issue by MeABc** [yinqiwen/gsnova#53]
@yinqiwen 

大改了，是不是不支持 （heroku）pass 了？谢谢！

**Comment by MeABc** [comment]
是不是全部统一到 remote/server 里了？

**Comment by yinqiwen** [comment]
支持heroku，合并到remote/server了
remote/server/Procfile 就是heroku的启动设置

**Comment by MeABc** [comment]
还有一个问题：
Procfile 里有一个 key ，和 server.json 里面 key 区别是什么？保持一样吗？

**Comment by yinqiwen** [comment]
没有server.json情况下支持命令行指定，不需要配置文件

**Comment by MeABc** [comment]
了解。

**Comment by MeABc** [comment]
![image](https://user-images.githubusercontent.com/18194126/29854016-00e9d8e6-8d76-11e7-9c2b-0c4fb796a7af.png)

这样是不是说明服务端没有部署成功。

**Comment by MeABc** [comment]
我自己的问题。。。。
已确认刚才没有部署成功。。。。

**Comment by MeABc** [comment]
找到原因了： server.json 优先级比 Procfile 高。一旦加 server.json 就会出错，$PORT 绑定错误。

所以，想问，我想设置认证应该怎么做呢？或者说怎么在 Procfile 里加认证，没有用 server.json 。

**Comment by MeABc** [comment]
![image](https://user-images.githubusercontent.com/18194126/29855975-567d49bc-8d82-11e7-9dfb-7b22c73687d4.png)

搞定了。

**Comment by MeABc** [comment]
另用这地方记录一下。

```
# https://github.com/heroku/heroku-buildpack-go
$ heroku config:set GOVERSION=go1.9
```

**Comment by MeABc** [comment]
![image](https://user-images.githubusercontent.com/18194126/29857794-04d179fc-8d8d-11e7-9aa4-74d2b2975887.png)

@yinqiwen 你有空看下这个。

**Comment by yinqiwen** [comment]
@MeABc  改成socks5 proxy试下，这个是试图读取http 请求但出错了

**Comment by devcodewak** [comment]
@yinqiwen ,请看下gitter

openshifit v3 docker 170830_0c11eda 版，部署ok.

我这里o3比heroku快些，sni下

**Comment by yinqiwen** [comment]
@devcodewak  openshift 可以选west US， 可能物理距离更近
