### ISSUE TITLE
Several question about server.conf

### ISSUE THREAD

**Issue by testcaoy7** [yinqiwen/gsnova#56]
Readme tells little about server.conf and client.conf. 

Howto generate key used for encryption ?
Can cipher be defined at server.conf ? Or server will auto-match client setting ?
Can application layer packet encryption be disabled and only use TLS or QUIC (transport layer) for security ?

What does "UDPGW" do ?
What does local "Admin" do ?

**Comment by yinqiwen** [comment]
the key is just simple  string, u can  use 'abceasdasdasdasas' instead.    
Currently, cipher is chosen by client, and server would accept the selected one for the later data communication.    
The encryption is disabled if the transport channel is `https/wss/tls`.   https://github.com/yinqiwen/gsnova/blob/master/local/proxy/proxy.go#L168 
  

`UDPGW` is udp gateway which used to serving udp traffic redirected by tun2socks(used in android).   
`Admin` is a local http server to monitor internal running state.

**Comment by testcaoy7** [comment]
I see. Thank you.
