### ISSUE TITLE
dropbox deploy gsnova-paas v0.29 的问题。

### ISSUE THREAD

**Issue by distance00** [yinqiwen/gsnova#65]
总是提示Unable to lock Dropbox。
试了很多次，刚似乎莫名其妙成了一次，我再试试看。

**Comment by distance00** [comment]
显示r10.1是不是成了？但还是出错，我就是用老版服务端，换新版客户端提示这个错误才升级的。
[ERROR]Failed to create mux session for wss://
xxxxx.herokuapp.com:0 with reason:EOF
 [ERROR]Proxy channel:heroku-websocket init fai
led

**Comment by yinqiwen** [comment]
@distance00 服务端是没有修改的；可能是客户端的问题

**Comment by distance00** [comment]
我以前的服务端很老，显示是r4，客户端到r9还能用，也就是v0.26.4。后面版本都是那个错误提示。
“成了”的那一次，我怀疑是不是成了，因为提示还是出错，先是无限卡在 Receive code from Dropbox，刷新一次就提示Unable to lock Dropbox。但换老的r4部署一次就成，完全正常。

**Comment by distance00** [comment]
有人说Unable to lock Dropbox是文件冲突？
https://stackoverflow.com/questions/28112056/unable-to-lock-dropbox-error-while-deploying-in-heroku

**Comment by yinqiwen** [comment]
应该是heroku的问题， 用heroku 命令行工具吧。

**Comment by distance00** [comment]
一直用的dropbox，heroku如果有问题，为什么老版本一次就成呢，奇怪。

**Comment by distance00** [comment]
我把两个版本共享了，谁有兴趣可以试一下，看看到底什么问题。
https://www.dropbox.com/sh/9okb5ta36opgfcv/AAAH66sp2b5l7o_M6nNS2Vqqa?dl=0

**Comment by distance00** [comment]
原因应该是新版太大了，所以容易出问题。比较了一下，体积与文件数量都暴增了10倍。今天重传了0.28（应该是一样的，只是心理作用，另外以防万一）， 经过漫长的Receive code from Dropbox，终于成功了。
由于文件太多太大，某个时段heroku稍有不稳，中间就会出问题。老大说是heroku的问题也是对的。

**Comment by yinqiwen** [comment]
@distance00 可以试下通过github sync， 应该没有相关的问题  https://devcenter.heroku.com/articles/github-integration

**Comment by distance00** [comment]
好的，下次更新的时候试试，用github是不是自己要在github上建个项目？

**Comment by yinqiwen** [comment]
是的

**Comment by distance00** [comment]
感谢说明，现在能用先不折腾了，下次更新的时候再试新方法吧。

**Comment by distance00** [comment]
很不幸的消息，新版速度明显不如老版，又退回去了，目前客户端r9，服务端r5，除了不断的报Websocket read error和 i/o timeout，用起来一切正常。

**Comment by yinqiwen** [comment]
包括r9之前client.json有个默认规则 国内IP或者不在GFWList中是直接连接的

**Comment by distance00** [comment]
新版r10.1的服务端r13的客户端才慢，视频卡顿，但我专门又试了googlevideo和twitch，都没有明显可以感觉到的差异，看来只针对特定的网站，无语了。决定两个版本都保存，说不定以后会遇到相反的情况。
GFWList和"IsCNIP"都从来没用过，事实上我把无关的全删了，只监听一个端口，只保留一条规则。刚好0.264这个版本也不检测apnic_cn.txt，干脆把这个文件删了，以后是把它清空，没有这个文件启动会报错。
卡顿我在不同的时段试了至少10次以上，都在相同的帐号上，一个新版一个老版，差异非常明显。

**Comment by yinqiwen** [comment]
新版本的增加了类似TCP滑动窗口的拥塞控制，最大只会缓存256K的数据 [initialStreamWindow](https://github.com/yinqiwen/pmux/blob/ca770cb564ccb2c963d6c23d5c4b1b6d8ed86298/const.go);  
旧版本没有这些，有多少发多少，所以类似视频类大流量的可能有这样的停顿现象

**Comment by distance00** [comment]
感谢解释，看来保存老版很有必要，新老版本不能兼容太可惜了。新版的cost to ping 出现的似乎过于频繁了，不管有没有在用，每次看都是满屏的cost to ping，淹没了真正有用的信息。

**Comment by distance00** [comment]
关于那个拥塞控制，如果有个参数能控制就好了。

**Comment by distance00** [comment]
非常感谢。
看下我这里的cost to ping，不停的往上滚，每秒都在刷新，只有这个，看不到别的内容。我只用paas，放了4个。
2017/10/27 18:16:21 proxy.go:144: Cost 447.0255ms to ping remote:wss:/
herokuapp.com
2017/10/27 18:16:23 proxy.go:144: Cost 365.0209ms to ping remote:wss:/
erokuapp.com
2017/10/27 18:16:23 proxy.go:144: Cost 238.0136ms to ping remote:wss:/
.herokuapp.com
2017/10/27 18:16:24 proxy.go:144: Cost 254.0145ms to ping remote:wss:/
herokuapp.com
2017/10/27 18:16:26 proxy.go:144: Cost 276.0157ms to ping remote:wss:/
erokuapp.com
2017/10/27 18:16:27 proxy.go:144: Cost 260.0148ms to ping remote:wss:/
herokuapp.com
2017/10/27 18:16:27 proxy.go:144: Cost 258.0147ms to ping remote:wss:/
herokuapp.com
2017/10/27 18:16:27 proxy.go:144: Cost 285.0163ms to ping remote:wss:/
.herokuapp.com
2017/10/27 18:16:28 proxy.go:144: Cost 309.0177ms to ping remote:wss:/
herokuapp.com
2017/10/27 18:16:30 proxy.go:144: Cost 363.0207ms to ping remote:wss:/
herokuapp.com

**Comment by distance00** [comment]
试了一下openshift，部署不了，无限卡在 Rolling deployment is pending，   View Events里面自从开始Deployment created，就不断的Failed scheduling  
No nodes are available that match all of the following predicates:: Insufficient memory (165), MatchNodeSelector (5).
Insufficient memory后面的数字从16x到17x
Image是创建成功的，从builds images中可以看到
Digest
sha256:df228c84e688ecb688b8570f4c7db3a524f3164f61ec67c86b1b6b0aa2e70808
Identifier
sha256:865f43277dbad2aeae65743026b1dd68fd224102f548c567ea8fc38204225616
Container也创建成功
Containers
CONTAINER: GSNOVA-PAAS
Image: gsnova/gsnova-paas df228c8 159.4 MiB
Ports: 9443/TCP, 9444/TCP

**Comment by distance00** [comment]
老大能不能在dokerhub上建个0.26.4版的？这个版短小精悍，部署成功率高太多了。
前面也有人反映0.28的无法部署，以前0.26的没有问题。
有大的更新了，前面的经典版本也应该有个备份嘛。

**Comment by MeABc** [comment]
最新版本服务端提示“用户无效”！！

![image](https://user-images.githubusercontent.com/18194126/32129727-5be2a7c6-bbbd-11e7-98f0-cca5ac63b4cb.png)

@yinqiwen

**Comment by MeABc** [comment]
![image](https://user-images.githubusercontent.com/18194126/32129774-f4a6be52-bbbd-11e7-9c64-99c880171583.png)

客户端。

提示用户不对，没道理啊。用户名应没有错的。

**Comment by MeABc** [comment]
基本可以确认了----改成 `-allow "*"` 就没有问题。
@yinqiwen 你再确认一下。

**Comment by distance00** [comment]
稍有进展，创建了pod以后，又是连续的 Insufficient memory，最终fail
Status:  Failed
  | --> Scaling gsnova-paas-1 to 1
-- | --
  | --> Waiting up to 10m0s for pods in rc gsnova-paas-1 to become ready
  | W1028 01:21:41.194696       1 reflector.go:323] github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:509: watch of *api.Pod ended with: too old resource version: 283840596 (283840622)
  | error: update acceptor rejected gsnova-paas-1: pods for rc "gsnova-paas-1" took longer than 600 seconds to become ready

**Comment by distance00** [comment]
@MeABc  你服务端有没有改"Key"？客户端不要改，保持原样就没问题。

**Comment by yinqiwen** [comment]
@distance00  部署openshift v3不是用dockerv3方式？

**Comment by yinqiwen** [comment]
@MeABc  * 在shell里默认是个通配符会被展开为当前路径的所有文件名

**Comment by distance00** [comment]
我就直接到openshift注册，
登录以后在这里下载的windows版的command line tool 
https://console.starter-us-west-1.openshift.com/console/command-line
oc new-app gsnova/gsnova-paas
openshift会到dockerhub找到image
然后到console能看到创建过程，状态等。

**Comment by distance00** [comment]
另外最新版的服务端key改了没用，只认默认的那个，所以客户端如果也改了就出错，客户端别改就行了，我开始服务端偶尔部署好了一次还以为没好，因为这个出错信息和用老版服务端一样，几经周折，不断换版本试最后客户端的key忘了改了反倒好了。

**Comment by distance00** [comment]
差不多大于100兆的都部署不了，各种各样的错误。
phuslu/goproxy-php 只有3.5兆，两三分钟就部署成功，但是里面没有服务，创建不了路径。
gsnova/gsnova-paas 有159兆，0.26.4版镜像应该20来兆吧，部署应该也是一次成。
老大能否考虑一下，一个精简版，容易部署，默认够用，一个全能版要求高的去折腾？功能再多再好部署不了也是白搭呀。

**Comment by yinqiwen** [comment]
@distance00  比较大是因为这个dockerfile是从源码开始编译，可以用预编译的二级制的dockerfile

**Comment by kirbyzhu** [comment]
@distance00 能部署成功的，就是翻来覆去要很多次。

**Comment by devcodewak** [comment]
@distance00 @MeABc @kirbyzhu 
赞作者 yinqiwen 已建了新docker：   gsnova/gsnova-server
大小只有7M,  版本是  0.30.0 , 

https://github.com/yinqiwen/gsnova/blob/master/Docker/server/0.30.0/Dockerfile
https://hub.docker.com/r/gsnova/gsnova-server/tags/

**Comment by distance00** [comment]
@kirbyzhu 我有一次也很接近成功，要看运气和部署的时段，总之越大成功率越低。
@devcodewak 这样就太方便了，感谢作者。

**Comment by distance00** [comment]
@yinqiwen 请教一下新版的"Mux"客户端和服务端都有，两边设置不一致的话以哪个为准？是不是服务端只是设置个默认参数，可以通过客户端的设置来调节，如果客户端不设置就以服务端为准？

**Comment by yinqiwen** [comment]
@distance00 各自设置独立。如果是下载/视频这里下行流量大的，可以调整server； 如果是上行流量大调整client的

**Comment by distance00** [comment]
明白了，感谢说明。

**Comment by distance00** [comment]
0.30.0部署很快，只要两分钟，但“该网页无法正常运作”，用不用Secure route都一样，等很久都这样。有人试了吗？

**Comment by distance00** [comment]
159.4 M的新版竟然也几分钟就部署好了，但打开链接也显示“该网页无法正常运作”，然后变成
504 Gateway Time-out
The server didn't respond in time.
console里面看不出来有什么问题，是不是还需要设置环境变量或是添加config文件，感觉肯定哪里没弄对。

**Comment by distance00** [comment]
@devcodewak
又看了看，这两个版本是vps的吧，不过看说明
The server can also be deployed to serveral PAAS service like heroku/openshift

**Comment by distance00** [comment]
非常奇怪，最新版的gsnova-paas和gsnova-server都是159兆，（gsnova-paas上面写167，但实际上是159），但gsnova-server部署很快，一次成功，但gsnova-paas无论如何都部署不了，看来不光是大小的问题。

**Comment by distance00** [comment]
新版还有一个问题是频繁session shutdown
 session.go:244: [ERROR]: Failed to read frame: websocket: close 1006 (abnormal closure): unexpected EOF while decrypt counter 359021409 
session.go:356: [ERR] pmux: Failed to write frames: session shutdown
mux.go:97: [ERR]: Ping remote:wss://app.com failed: session shutdown
隔一会儿就出，老版就非常稳定。
还有一个无所谓的拼写问题。
mux.go:159: Mux session woulde expired after 302 seconds.

**Comment by MeABc** [comment]
![1](https://user-images.githubusercontent.com/18194126/32202185-f23de99c-be15-11e7-8d90-f93fea234bdc.png)
![2](https://user-images.githubusercontent.com/18194126/32202187-f337e9e2-be15-11e7-9d24-8dc750a619e8.png)

还是接我上面的话题----用户认证。
上面两张图是我加了一些调试信息。（重复部份是我复制粘贴多了，不是源码问题。）

可以看出，服务端读取“用户”没问题(go:79)；但验证有问题(go:81)，传入为空字符？又或者客户端没有发“用户名”？

**Comment by yinqiwen** [comment]
@MeABc  client.json 里配置在 “Cipher”:{"User":"xx"} 中

**Comment by MeABc** [comment]
@yinqiwen 嘎嘎，我白痴了。项目 readme 就有。谢谢。

**Comment by MeABc** [comment]
@yinqiwen 请问，关于 gsnova ping 的问题：我这实际上 ping heroku paas 是不通的；所以，能不能关掉它。不然老是有这种“错误”：
![image](https://user-images.githubusercontent.com/18194126/32874109-19c65dac-cacb-11e7-977b-e08ea4c1f26a.png)

**Comment by MeABc** [comment]
对了，我要是把这两行注释了，有没有什么副作用 :)
[mux.go#L97](https://github.com/yinqiwen/gsnova/blob/master/common/channel/mux.go#L97)

**Comment by yinqiwen** [comment]
@MeABc  ping是在TCP连接里发TCP包， 如果不通那么说明要么连接延迟太高，要么远程服务有问题。
注释掉ping除了会造成引起发现连接问题比较晚的问题，没有其它逻辑上的影响

**Comment by MeABc** [comment]
@yinqiwen 谢谢！我先试下效果。

**Comment by distance00** [comment]
事实上有时候出现这种情况后提示“no proxy for this session”（凭印象，大概这个意思）没法用，重启就一切正常了。不知道是不是连到了不同的ip还是怎么回事。

**Comment by distance00** [comment]
里面有FastDNS和Trusted，是优先用Fast吗？什么时候用Trusted？会不会是用了不同的DNS？连续红字Ping failed，重启一切正常，一次红字也没有了。当然不是每次都解决问题。

**Comment by distance00** [comment]
openshift虽然就两个ip，但有时候会在不同的位置，west2的一个在密歇根，一个就真的在俄勒冈。刚开始时候canada的实际在密歇根，现在真的在加拿大。

**Comment by yinqiwen** [comment]
@distance00 可以把ReconnectPeriod调小，目前是3000s；这个是定期主动断开连接重连

**Comment by distance00** [comment]
看了一下，老版是30，忘了以前有没有改过，新版的是300（专门重新下了一个），改小点试试看，不太理解，ping failed重连怎么会好，重连多了不影响稳定性吗。

**Comment by lovemyself1214** [comment]
@distance00  问一下 你的这个问题是怎么解决的啊 Failed scheduling
No nodes are available that match all of the following predicates:: Insufficient memory (165), MatchNodeSelector (5).

**Comment by distance00** [comment]
@lovemyself1214 解决不了，服务器资源不够，重新注册一个，换服，加州的现在第一步都schedule不上，加拿大的运气好的话一次成。

**Comment by lovemyself1214** [comment]
@distance00  好吧，先不弄了。

**Comment by lovemyself1214** [comment]
@distance00  我部署好了，再问你个问题，这个客户端配置文件里怎么写啊？不太懂，不要笑。先谢谢了。

**Comment by distance00** [comment]
只用pass的话，可以简化成这样，route是edge，监听8088
`
{
	"Log": ["color"],
	"UserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36",
	"Cipher":{"Method":"auto", "Key":"809240d3a021449f6e67aa73221d42df942a308a"},
	"Mux":{
		"MaxStreamWindow": "512K",
		"StreamMinRefresh":"32K"
	},

	"User": "gsnova",
    "LocalDNS":{
    	"Listen": "127.0.0.1:5300",
    	"FastDNS":["223.5.5.5","180.76.76.76"],
    	"TrustedDNS": ["208.67.222.222", "208.67.220.220"]
	},
	"UDPGW":{
		"Addr":"20.20.20.20:1111"
	},
	"Proxy":[			
		{
			"Local": ":8088",
			"PAC":[
				{"Remote":"openshift-ca"}
			]
		}
	],
	"Channel":[
		{
		    "Enable":true,
			"Name":"openshift-ca",
			"ServerList":[
			"wss://xxxxxxx.openshiftapps.com"
			],
	        "Proxy":"",
		    "ConnsPerServer":3,
			"RemoteDialMSTimeout":5000,
			"RemoteDNSReadMSTimeout":1500,
			"RemoteUDPReadMSTimeout":15000,
			"LocalDialMSTimeout":5000,
		    "ReconnectPeriod": 300,
		    "RCPRandomAdjustment" : 10,
			"HeartBeatPeriod": 30,
			"Compressor":"none",
			"Hops":[]
		}
	]
}
`

**Comment by lovemyself1214** [comment]
@distance00  弄好了，非常感谢.

**Comment by kirbyzhu** [comment]
这个里面serverlist能不能多个paas server并行工作啊？
另外在host.json里面设置了sni 但是好像没有速度提升啊

**Comment by distance00** [comment]
@kirbyzhu
可以多个，但不知能不能流量平衡
host.json并非前置。

**Comment by distance00** [comment]
@yinqiwen
在别处用的好好的sni拿到这里用不了是怎么回事？直接用一直是local_server.go:198: Connect failed from proxy connection for reason:dial tcp xx.xx.xx.xx:443: i/o timeout
前置倒是能用，虽然也会时不时的timeout。
虽然对inhosts的direct有点不确定（记得以前是TLSDirect，前面还有SNISniff），但不应该一直timeout，即使它不稳定。
很久没用sni了，有一段时间用gsnova只用sni，自从sni大面积实效以后就没再用过。

**Comment by kirbyzhu** [comment]
@distance00 谢谢解答

**Comment by distance00** [comment]
@yinqiwen 
我的具体操作步骤，全新下载0.31，去掉"InHosts"这个"Rule"的注释，在hosts中指向insip，insip在v2ary和goproxy中都可以用（前置），以前都是这样用的，现在用不了了是怎么回事？还有哪里需要配置吗？

**Comment by distance00** [comment]
专门测试了一番，原来是墙的问题，开始看到dial  timeout，没往这上面想，看起来是专门针对sni另外加的规则，因为个别直接访问被墙的网站用外网的sni还能直接转，比较有名的都不行。这也解释了为什么能前置，但是另人困惑的是，为什么goproxy还能前置？1e100.net也是被墙的呀。要么可以参照goproxy找到一种直接用的方式，要么是1e100.net没进名单，被警觉了瞬间被墙。

**Comment by yinqiwen** [comment]
@distance00  SNI在gsnova的应用方式是直连透传，不会修改TLS协议的SNI； 如果有不一样的行为的话，goproxy应该是修改了TLS的连接机制，这需要安装伪证书通过类似中间人攻击方式实现。（记得goproxy是自动生成伪CA证书的）

**Comment by distance00** [comment]
goproxy的SiteToAlias也有一点让人非常不解，它是设置直连的，本来一切“正常”，你访问google显示你本地ISP的地址，跟把ip放进hosts一样直连了，你放sni进去，访问google显示你sni所在地的地址，也（似乎）跟你放hosts里面一样直连了，但是你在SiteToAlias里面放一个非google的地址，问题来了，显示404，而且是google的404，它的直连似乎也还是以某种方式通过了google？

**Comment by distance00** [comment]
用了sni前置后ping failed session shutdown的问题变得异常突出，不是随机的了，而是固定几十秒就fail shutdown，重连设置很短，每次重连都完全正常，如此不断重复。直接用一切正常，sni直接用也非常稳定。感觉真的没必要不断的去ping，反正一会儿就要重连，连上就不管它了多好。ping个10次有一次timeout基本不会影响使用，但shutdown了又没有重连就影响使用了。

**Comment by lovemyself1214** [comment]
@distance00  heroku 免费账户每个月都有使用时间限制？

**Comment by distance00** [comment]
@lovemyself1214 似乎新注册的有限制，具体不清楚，你使用发现时间限制了吗？具体什么情况？

**Comment by lovemyself1214** [comment]
@distance00 https://devcenter.heroku.com/articles/free-dyno-hours 我这个注册了最少两年了吧 具体什么时候注册的记不清了。

**Comment by distance00** [comment]
@lovemyself1214 这应该就是新的条款吧，[Billing page](https://dashboard.herokuapp.com/account/billing)怎么打不开，一个应用应该只占一个dyno对吧，不管你同时发起多少连接。这样的话550小时自己用的话怎么都够了。另外据说heroku不允许proxy类的应用，从来没看过条款，也不知道在哪，不过最好还是低调，有别的用优先用别的。

**Comment by distance00** [comment]
@yinqiwen 配置中有4个Timeout，不知道是哪个导致了shutdown？从一个外行的角度来看，既然在不断ping它的连通性，是不是就不用定期断开重连了？ping不通了自动断开重连，ping的通就一直保持连接。有前置的情况下怎么ping的，通过前置来ping服务端的连通性？前置或服务端不允许ping怎么办？很多sni都不允许ping，有人自己的vps为了隐身也不让ping。

**Comment by devcodewak** [comment]
@distance00 
一、
你指的ping是log里的 “proxy.go:143: Cost 251.7763ms to ping remote:http2:// ......" 吧，

这个ping代表了心跳，是协议内测试通讯来回速度、维持链路用的。参数是：HeartBeatPeriod ，不是通常的 icmp echo 报文。

这个心跳通常是需要的，例如大部分sni会检测是否有数据传输，如无一定时间后（不同sni 25s-60s不等），会强制断开tcp链接。 有心跳则不会断，可保持长连接。

二、
ReconnectPeriod 是定期重连，单位是秒，作者设置的比较小，如想长连接（例如保持ssh），可配几小时即可。 长连接和定时重连，各有利弊，看需求。

三、
个人看法，心跳和重连，还是作者这么分开设计最好。关联起来反而复杂化。

**Comment by distance00** [comment]
@devcodewak 感谢说明，不过看上面有人注释掉ping，不懂代码，只是有点受不了那个shutdown。其实heroku我还是一直用0.26，经过反复比较，还是0.26的稳定，速度快。0.26的重连默认30秒，也许也会shutdown但log中没有显示而已？但速度快是真的，新版mux调到1m以上还是不能比。

**Comment by MeABc** [comment]
@distance00 

呃，我上面注释也是测试用的。。

以下是我对 gsnova 代码的修改。如有不对请指出。

```
1.
https://github.com/yinqiwen/gsnova/blob/master/common/channel/websocket/remote.go
var (
	upgrader = websocket.Upgrader{
		ReadBufferSize:  1024 * 1024 * 4,
		WriteBufferSize: 1024 * 1024 * 4,
	}
)
--
2.
https://github.com/yinqiwen/pmux/blob/master/config.go

EnableKeepAlive:        true,
改成：
EnableKeepAlive:        false,

PingTimeout:            5 * time.Second,
改成：
PingTimeout:            10 * time.Second,
---
3.
https://github.com/yinqiwen/gsnova/blob/master/common/channel/mux.go
348行
func expireLocalChannels() {
	if !atomic.CompareAndSwapInt32(&expireTaskLauched, 0, 1) {
		return
	}
	ticker := time.NewTicker(10 * time.Second)
改成：
func expireLocalChannels() {
	if !atomic.CompareAndSwapInt32(&expireTaskLauched, 0, 1) {
		return
	}
	ticker := time.NewTicker(5 * time.Second)
--
```

以上修改只用在 sni + heroku ，其它环境可能不适用。

**Comment by MeABc** [comment]
经过上面的修改， session shutdown 这个“错误”几乎没有了。呃，目前我也说不出个所以然来。。。
不过又出现新“错误”：
```
mux.go:97: [ERR]: Ping remote:wss://xxxxx.herokuapp.com failed: i/o deadline reached
```

又，openshift V3 没有用过，好吧，我承认我从来就没有部署成功过，已搞到怀疑人生。

**Comment by lovemyself1214** [comment]
@MeABc 服务器换到加拿大的就可以啦，美国的我也是怎么也不成。
@distance00 以前一直用goproxy啊，可是开大会的时候，一下突然就再也用不了了，任何扫描IP的工具一个可用IP都扫不到，我是突然一下就不能用了，然后就再也没有然后了。goproxy的php-go也部署在heroku上的，而且goproxy手机上用着不那么友好。550小时确实够用了。再不行，就只能自己买vps了。暂时能用一天算一天吧。

**Comment by distance00** [comment]
@MeABc 代码不懂，关键是还要编译，超出折腾的范围了。加州的想部署成功跟中奖一样，每天有空都进去试试，运气好说不定哪次能成，加拿大的新开不久一般都能一次成。
最喜欢gsnova的一点是它内置pac和hosts，可以灵活配置，如果能在pac中调用别的代理就完美了，即使不用gsnova的服务端也可以用它统一管理，这样就成了人手必备的工具了。有个缺点是启动慢，它要把服务端都连一遍才能启动，启动成功之前连sni都不能用。
一直用privoxy调度系统代理，最近发现一个问题无法解释，stunnel用privoxy后严重影响速度，privoxy就是简单的把网址指向代理而已，比如forward .example.com 127.0.0.1:2080，stunnel用privoxy forward后居然变卡，直接设成系统代理就没问题。百思不得其解，别的代理都没发现问题。

**Comment by distance00** [comment]
@lovemyself1214 goprxoy ipv6还能用，quic还能扫到零星的ip，不过感觉随时会失效，有种朝不保夕的感觉，买vps便宜的还不如免费的，估计除非香港的或是双程cn2，以前用goproxy的那种感觉是找不回来了，那时候都不分高峰期的，任何时候都流畅。

**Comment by MeABc** [comment]
@distance00 @lovemyself1214 谢谢！有空换加拿大的试下。

**Comment by MeABc** [comment]
@distance00 
stunnel 没有用过，不是很了解，这个说不上话了。。。

**Comment by distance00** [comment]
@lovemyself1214 把xx net的ip库拿来扫，一百万个中间能扫到几十个，都是边远小国的，速度慢，没有多少实用价值，看地区和isp吧，有人能扫到一些高速的。

**Comment by lovemyself1214** [comment]
@distance00 一个也扫不到，以前有人分享的几百W的IP库也是一个也扫不到，不管是gscan quic  还是MMF,xx-net 一个也扫不出来，开大会之前，从来没有过这种情况，从goagent到goproxy。一直用的好好的，直到这次开大会。

**Comment by distance00** [comment]
@lovemyself1214 应该是地区差异吧，有的地方ipv6也开始失效了，还是趁早多找几个后路，免得到时候手忙脚乱。

**Comment by distance00** [comment]
@yinqiwen  请教一下新版的0Pensh1ft部署以后不能用是什么问题？
比如部署gsn0va-paa3， 8080， edge。这个是最简单的，部署后页面可以开，表示部署是成功的。
运行后控制台里面显示：online.com:0 bad handshake。
online.com:0后面的端口0是怎么回事？可以改吗？需要改镜像吗？谢谢。
在客户端改的话成了online.com:443:0

**Comment by distance00** [comment]
以前克隆的镜像，0Pensh1ft改版前可以用。
gohergo/novava

**Comment by distance00** [comment]
@yinqiwen 以前克隆的镜像，0Pensh1ft改版前可以用。
gohergo/novava
