### ISSUE TITLE
heroku+gsnova，连接时卡在Request CONNECT

### ISSUE THREAD

**Issue by ocrinz** [yinqiwen/gsnova#83]
heroku+gsnova，偶尔能连上，但大多数时候都卡在在c4.go:271 Request CONNECT。
请问这是什么原因（是配置问题还是别的什么问题），该怎么解决呢？谢谢！

**Comment by yinqiwen** [comment]
用最新的部署，c4.go已经是好几年前的版本了

**Comment by ocrinz** [comment]
谢谢，我试试
