### ISSUE TITLE
关于服务端

### ISSUE THREAD

**Issue by THLIVSQAZ** [yinqiwen/gsnova#85]
在vps上使用gsnova,但从文档上看貌似没有以服务后台运行的参数，只能用ssh前端执行。
请问作者有解决办法吗？
谢谢y大

**Comment by yinqiwen** [comment]
用supervisor控制  http://supervisord.org/

**Comment by THLIVSQAZ** [comment]
好主意，不过最后用docker实现了后台

**Comment by yinqiwen** [comment]
这个说明已经同步了
或者PC的7788端口的服务上没有相关的配置文件

**Comment by THLIVSQAZ** [comment]
那如何在pc端添加配置文件？
在gsnova所在目录内放android配置文件？

**Comment by yinqiwen** [comment]
看这里
https://github.com/yinqiwen/gsnova/issues/55

**Comment by THLIVSQAZ** [comment]
好的，我试试

**Comment by THLIVSQAZ** [comment]
按照 #55 和 #58 同步成功，谢谢y大

**Comment by yinqiwen** [comment]
应该是的，TLS 验证失败

**Comment by THLIVSQAZ** [comment]
墙的动作可真快
