### ISSUE TITLE
GSnova在个人VPS上部署成功，但客户端无法成功验证

### ISSUE THREAD

**Issue by raichuP** [yinqiwen/gsnova#87]
服务商Virmach，使用CentOS 7，防火墙相关端口已开放tcp连接。
客户端运行后遇到如下信息，并确认无法正常连接：
![qq 20180810093345](https://user-images.githubusercontent.com/34131728/43951237-263f87e6-9c82-11e8-987c-6c9a2da7ca79.png)
已检查核实Key一致，均为默认值。
client.json有改动部分相关配置如下：
![qq 20180810093910](https://user-images.githubusercontent.com/34131728/43950960-5ba44fee-9c81-11e8-8ea9-e7b6e9d93160.png)

**Comment by yinqiwen** [comment]
看下server的日志，一般udp受限的条件比较多

**Comment by yinqiwen** [comment]
配置有问题，  kcp那一行去掉吧

**Comment by raichuP** [comment]
![qq 20180810095750](https://user-images.githubusercontent.com/34131728/43951892-e67f2b64-9c83-11e8-9c3b-a183afa84a03.png)
仅保留tcp配置后报错I/O timeout

**Comment by yinqiwen** [comment]
这个就要看server的日志有没有TCP连接进入了

**Comment by yinqiwen** [comment]
这个ip port有问题，我在hk 的vps 也无法连上

`telnet: connect to address ******: No route to host`

**Comment by raichuP** [comment]
`2018/08/10 05:56:18 remote.go:40: Listen on TCP address::48100
2018/08/10 05:56:18 remote.go:30: Listen on QUIC address::48100
2018/08/10 05:56:18 web.go:42: Listen on HTTP address::48102
2018/08/10 05:56:18 remote.go:52: Listen on TLS address::48101
2018/08/10 05:56:18 remote.go:28: Listen on KCP address::48101
2018/08/10 05:56:18 remote.go:118: Listen on HTTP2 address::48103
`
我的服务端运行后除配置外只有这些信息且不再更新，是否意味着未成功运行？

**Comment by raichuP** [comment]
彻底关闭防火墙服务后发现可以正常运行，谢谢您的帮助
